### ISSUE TITLE
Add USSD Field Response Validators

### ISSUE THREAD

**Issue by Timtech4u** [ushahidi/platform-api-ussd-service#11]
Add USSD Field Response Validations - and return messages to users on invalid responses.

**Comment by Timtech4u** [comment]
An approach I tried was to take users a **step** back if the value entered does not pass validation.
Since **step** is calculated off Ushahidi's POST data which is the sum of all user inputs (e.g. *0*1*Title  

Here*Description Here*...) - this makes it impossible to alter the POST data received when a User inputs an incorrect value and thus we're unable to take them a step back since.

A rather unfriendly approach I've seen in multiple USSD providers is to cancel the user's session once an incorrect value has been entered.

cc:  @tuxpiper

**Comment by tuxpiper** [comment]
I guess the only choice would be to keep track of which inputs were incorrect? The count of incorrect inputs could be subtracted from the step number to get the *real* step number ... 

Not pretty but 🤷‍♂

**Comment by Timtech4u** [comment]
> I guess the only choice would be to keep track of which inputs were incorrect? The count of incorrect inputs could be subtracted from the step number to get the _real_ step number ...
> 
> Not pretty but man_shrugging

:-D I'll try this, maybe would need tag the responses with a flag such as {validated: true}

**Comment by Timtech4u** [comment]
Discussions on using Redis are on #25
