### ISSUE TITLE
Explore Redis for persisting state across USSD session

### ISSUE THREAD

**Issue by Timtech4u** [ushahidi/platform-api-ussd-service#25]
Explore Redis for persisting state across USSD session

**Comment by Timtech4u** [comment]
I am currently able to save valid responses to Redis and ignore the invalid responses.
Would also be requesting the user to input responses for any invalid response. 

cc: @rowasc @tuxpiper

**Comment by rowasc** [comment]
wii, exciting!
Looking forward to a demo tomorrow :D
